#!/bin/bash

run_brew() {
	# Ask for the administrator password upfront.
	sudo -v

	# Keep-alive: update existing `sudo` time stamp until the script has finished.
	while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

	# Make sure we’re using the latest Homebrew.
	e_header "Updating brew..."
	brew update

	# Upgrade any already-installed formulae.
	e_header "Upgrading any already-installed formulae..."
	brew upgrade --all

	e_header "Installing default formulae..."

	# Install GNU core utilities (those that come with OS X are outdated).
	brew install coreutils
	sudo ln -fs /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

	# Install some other useful utilities like `sponge`.
	brew install moreutils
	# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
	brew install findutils
	# Install GNU `sed`, overwriting the built-in `sed`.
	brew install gnu-sed
	# Install Bash 4.
	brew install bash
	sudo bash -c 'printf "# List of acceptable shells for chpass(1).\n\
		# Ftpd will not allow users to connect who are not using\n\
		# one of these shells.\n\n\
		/usr/local/bin/bash\n\
		/bin/bash\n\
		/bin/csh\n\
		/bin/ksh\n\
		/bin/sh\n\
		/bin/tcsh\n\
		/bin/zsh\n" > /etc/shells'
	chsh -s /usr/local/bin/bash
	brew install bash-completion
	brew install rsync
	brew install nano
	brew install less
	brew install wget --with-iri
	brew install vim --override-system-vi
	brew install homebrew/dupes/screen
	brew install homebrew/dupes/openssh
	brew install homebrew/dupes/grep
	brew install sfnt2woff
	brew install sfnt2woff-zopfli
	brew install woff2
	brew install trash

	brew cask install java7
	brew cask install java
	brew install maven
	brew install node
	brew install git-flow-avh

	brew cask install qlcolorcode
	brew cask install qlstephen
	brew cask install qlmarkdown
	brew cask install quicklook-json
	brew cask install qlprettypatch
	brew cask install quicklook-csv
	brew cask install betterzipql
	brew cask install qlimagesize
	brew cask install webpquicklook
	brew cask install suspicious-package

	brew cask install arrsync
	brew cask install airdroid
	brew cask install android-studio
	brew cask install appcleaner
	brew cask install caffeine
	brew cask install clipmenu
	brew cask install dbeaver-enterprise
	brew cask install eclipse-jee
	brew cask install google-chrome
	brew cask install google-chrome-canary
	brew cask install firefox
	brew cask install mamp
	brew cask install onyx
	brew cask install postman
	brew cask install skim
	brew cask install sourcetree
	brew cask install skype
	brew cask install spotify
	brew cask install staruml
	brew cask install steam
	brew cask install sublime-text
	brew cask install telegram
	brew cask install the-unarchiver
	brew cask install virtualbox
	brew cask install transmission
	brew cask install cockatrice
	brew cask install istat-menus
	brew cask install intellij-idea
	brew cask install webstorm
	brew cask install mactex
	brew cask install texstudio
	brew cask install evernote
	brew cask install whatsapp
	brew cask install kobox
	brew cask install daisydisk
	brew cask install slack

	brew cleanup
	brew cask cleanup
}
