#!/bin/bash

run_brew() {
	# Ask for the administrator password upfront.
	sudo -v

	# Keep-alive: update existing `sudo` time stamp until the script has finished.
	while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

	# Make sure we’re using the latest Homebrew.
	e_header "Updating brew..."
	brew update

	# Upgrade any already-installed formulae.
	e_header "Upgrading any already-installed formulae..."
	brew upgrade --all

	e_header "Installing default formulae..."

	brew install bash
	sudo bash -c 'printf "# List of acceptable shells for chpass(1).\n\
		# Ftpd will not allow users to connect who are not using\n\
		# one of these shells.\n\n\
		/usr/local/bin/bash\n\
		/bin/bash\n\
		/bin/csh\n\
		/bin/ksh\n\
		/bin/sh\n\
		/bin/tcsh\n\
		/bin/zsh\n" > /etc/shells'
	chsh -s $(which bash)
	brew install bash-completion
	brew install trash
	brew install ideviceinstaller
	brew install ios-webkit-debug-proxy

	brew cask install java
	brew install node

	brew cask install qlcolorcode
	brew cask install qlstephen
	brew cask install qlmarkdown
	brew cask install quicklook-json
	brew cask install qlprettypatch
	brew cask install quicklook-csv
	brew cask install betterzipql
	brew cask install qlimagesize
	brew cask install webpquicklook
	brew cask install suspicious-package

	brew cask install airdroid
	brew cask install appcleaner
	brew cask install caffeine
	brew cask install google-chrome
	brew cask install mamp
	brew cask install onyx
	brew cask install skim
	brew cask install sourcetree
	brew cask install skype
	brew cask install spotify
	brew cask install the-unarchiver
	brew cask install virtualbox
	brew cask install cyberduck
	brew cask install dropbox
	brew cask install flux
	brew cask install google-earth
	brew cask install phpstorm
	brew cask install sketch
	brew cask install skitch
	brew cask install skyfonts
	brew cask install vlc
	brew cask install vuze
	brew cask install sublime-text
	brew cask install clip-menu

	brew cleanup
	brew cask cleanup
}
