#!/bin/bash

run_sublime() {
	INSTALLED_PACKAGES_DIR="${HOME}/Library/Application Support/Sublime Text 3/Installed Packages"
	USER_DIR="${HOME}/Library/Application Support/Sublime Text 3/Packages/User"
	PKG="./extra/sublime/packages"
	SETTINGS="./extra/sublime/settings"

	mkdir -p "${INSTALLED_PACKAGES_DIR}"
	mkdir -p "${USER_DIR}"
	
	for setting in "${SETTINGS}"/*; do
		cp "${setting}" "${USER_DIR}"
	done

	for package in "${PKG}"/*; do
		cp "${package}" "${INSTALLED_PACKAGES_DIR}"
	done
}
